### ISSUE TITLE
Error occurred while enabling GenCore v1.6.2-R1 (Is it up to date?)

### ISSUE THREAD

**Issue by GreenArrowlol** [summiner/GenCore#4]
This issue occurs as soon as I do changes by adding a new gen or editing the default gen
```
[03:41:21 ERROR]: Error occurred while enabling GenCore v1.6.2-R1 (Is it up to date?)
de.tr7zw.changeme.nbtapi.NbtApiException: [?]Error while calling the method 'putBoolean(java.lang.String,boolean)', loaded: true, Enum: COMPOUND_SET_BOOLEAN Passed Class: class java.lang.Boolean
        at de.tr7zw.changeme.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:185) ~[GenCore-1.6.3.jar:?]
        at de.tr7zw.changeme.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:611) ~[GenCore-1.6.3.jar:?]
        at de.tr7zw.changeme.nbtapi.NBTCompound.setBoolean(NBTCompound.java:385) ~[GenCore-1.6.3.jar:?]
        at com.gencore.gens.Generator.<init>(Generator.java:27) ~[GenCore-1.6.3.jar:?]
        at com.gencore.GenCore.addGenerator(GenCore.java:94) ~[GenCore-1.6.3.jar:?]
        at com.gencore.GenCore.lambda$setupGenerators$1(GenCore.java:129) ~[GenCore-1.6.3.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.gencore.GenCore.setupGenerators(GenCore.java:121) ~[GenCore-1.6.3.jar:?]
        at com.gencore.GenCore.onEnable(GenCore.java:150) ~[GenCore-1.6.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-160]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-160]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-160]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at de.tr7zw.changeme.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:183) ~[GenCore-1.6.3.jar:?]
        ... 20 more
[03:41:21 INFO]: [GenCore] Disabling GenCore v1.6.2-R1
```

**Comment by EquipableMC** [comment]
Spoke with the creator, this only works up to 1.18.2, and I don’t know about about 1.19-1.19.4, it’s untested
